regress:
	./runreg.py regress

clean:
	rm -f *.test *.timing_gpu *.pass 

clean-parts:
	rm -f *.deg *.part.mtx*

clean-gold:
	rm -f *.gold *.timing

clean-timings:
	rm -f *.timing *.gpu_timing

clean-all: clean clean-gold clean-parts clean-timings
